apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: airflow
  labels:
    app: airflow
    component: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      component: webserver
  template:
    metadata:
      labels:
        app: airflow
        component: webserver
    spec:
      containers:
        # Airflow Webserver 컨테이너
        - name: webserver
          image: apache/airflow:2.5.0
          ports:
            - containerPort: 8088
          env:
            # SQLAlchemy 연결 정보 (PostgreSQL)
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: "postgresql+psycopg2://airflow:airflow@postgresql/airflow"
            # CeleryExecutor의 결과 백엔드
            - name: AIRFLOW__CELERY__RESULT_BACKEND
              value: "db+postgresql://airflow:airflow@postgresql/airflow"
            # CeleryExecutor 브로커 URL
            - name: AIRFLOW__CELERY__BROKER_URL
              value: "redis://redis:6379/0"
            # 추가 설정: DAGs 경로
            - name: AIRFLOW__CORE__DAGS_FOLDER
              value: /opt/airflow/dags
          volumeMounts:
            - name: airflow-dags
              mountPath: /opt/airflow/dags

        # Git-Sync 컨테이너
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v3.3.0
          ports:
            - containerPort: 2222
          env:
            - name: GIT_SYNC_REPO
              value: "git@10.255.232.136:kube/airflow-dag.git"
            - name: GIT_SYNC_BRANCH
              value: "main"
            - name: GIT_SYNC_SSH
              value: "true"
            - name: GIT_SSH_KEY_FILE
              value: "/etc/git-secret/ssh-privatekey"
          volumeMounts:
            - name: git-secret
              mountPath: /etc/git-secret
              readOnly: true
            - name: airflow-dags
              mountPath: /dags

      # 볼륨 설정
      volumes:
        # DAGs 저장소
        - name: airflow-dags
          emptyDir: {}
        # Git-Sync SSH Secret
        - name: git-secret
          secret:
            secretName: ssh-airflow  # Git-Sync가 사용할 Secret 이름
