# Webserver Service
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: airflow
  labels:
    app: airflow
    component: webserver
spec:
  type: NodePort  # 외부 접근이 필요하면 LoadBalancer로 변경
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
  selector:
    app: airflow
    component: webserver

---

# Scheduler Service
apiVersion: v1
kind: Service
metadata:
  name: airflow-scheduler
  namespace: airflow
  labels:
    app: airflow
    component: scheduler
spec:
  type: ClusterIP
  ports:
    - port: 8793  # Scheduler API 포트
      targetPort: 8793
      protocol: TCP
  selector:
    app: airflow
    component: scheduler

---

# Worker Service
apiVersion: v1
kind: Service
metadata:
  name: airflow-worker
  namespace: airflow
  labels:
    app: airflow
    component: worker
spec:
  type: ClusterIP
  ports:
    - port: 8793  # Worker 간 통신용 포트
      targetPort: 8793
      protocol: TCP
  selector:
    app: airflow
    component: worker
