######################################################################
# [2024-12-26] Airflow - Customizing Configs by KTY                  #
######################################################################

aifrlow:
    image:
        repository: apache/airflow
        tag: 2.8.4-python3.9
        # Specifying digest takes precedence over tag.
        digest: ~
        pullPolicy: IfNotPresent
        # To avoid images with user code, you can turn this to 'true' and
        # all the 'run-airflow-migrations' and 'wait-for-airflow-migrations' containers/jobs
        # will use the images from 'defaultAirflowRepository:defaultAirflowTag' values
        # to run and wait for DB migrations .
        useDefaultImageForMigration: false
        # timeout (in seconds) for airflow-migrations to complete
        migrationsWaitTimeout: 60
        pod_template:
            # Note that `images.pod_template.repository` and `images.pod_template.tag` parameters
            # can be overridden in `config.kubernetes` section. So for these parameters to have effect
            # `config.kubernetes.worker_container_repository` and `config.kubernetes.worker_container_tag`
            # must be not set .
            repository: ~
            tag: ~
            pullPolicy: IfNotPresent
        flower:
            repository: ~
            tag: ~
            pullPolicy: IfNotPresent
        statsd:
            repository: quay.io/prometheus/statsd-exporter
            tag: v0.26.1
            pullPolicy: IfNotPresent
        redis:
            repository: redis
            # Redis is limited to 7.2-bookworm due to licencing change
            # https://redis.io/blog/redis-adopts-dual-source-available-licensing/
            tag: 7.2-bookworm
            pullPolicy: IfNotPresent
        pgbouncer:
            repository: apache/airflow
            tag: airflow-pgbouncer-2024.01.19-1.21.0
            pullPolicy: IfNotPresent
        pgbouncerExporter:
            repository: apache/airflow
            tag: airflow-pgbouncer-exporter-2024.06.18-0.17.0
            pullPolicy: IfNotPresent
        gitSync:
            repository: registry.k8s.io/git-sync/git-sync
            tag: v4.1.0
            pullPolicy: IfNotPresent

    # https://airflow.apache.org/docs/helm-chart/stable/index.html?source=post_page-----5bc5878f0c58--------------------------------
    # When installing the chart using Argo CD, Flux, Rancher or Terraform, 
    # you MUST set the four following values, 
    # or your application will not start as the migrations will not be run
    createUserJob:
        useHelmHooks: false
        applyCustomEnv: false
    migrateDatabaseJob:
        useHelmHooks: false
        applyCustomEnv: false
    ## the airflow executor type to use
    executor: KubernetesExecutor

    ## the fernet encryption key (sets `AIRFLOW__CORE__FERNET_KEY`)
    ## [FAQ] https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/security/set-fernet-key.md
    ## [WARNING] change from default value to ensure security
    fernetKey: "7T512UXSSmBOkpWimFHIVb8jK6lfmSAvx4mO6Arehnc="

    ## a list of users to create
    ## [FAQ] https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/security/airflow-users.md
    users:
        - username: airflow
          password: airflow
          role: Admin
          email: admin@example.com
          firstName: airflow
          lastName: admin

    ## configs generating the `pod_template.yaml` file for `AIRFLOW__KUBERNETES__POD_TEMPLATE_FILE`
    ## [NOTE] the `dags.gitSync` values will create a git-sync init-container in the pod
    ## [NOTE] the `airflow.extraPipPackages` will NOT be installed
    kubernetesPodTemplate:

        ## the full content of the pod-template file (as a string)
        ## [NOTE] all other `kubernetesPodTemplate.*` are disabled when this is set
        stringOverride: ""

        ## resource requests/limits for the Pod template "base" container
        ## [SPEC] https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#resourcerequirements-v1-core
        resources: {}

###################################
## Airflow log
###################################    
logs:
    persistence: 
        enabled: True
        existingClaim: pvc-poc-apache-airflow-log
        size: 1Gi


###################################
## COMPONENT | Airflow Webserver
###################################
web:
  ## the number of web Pods to run
  replicas: 1

  ## resource requests/limits for the web Pods
  ## [SPEC] https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#resourcerequirements-v1-core
  resources: {}

  ## configs for the Service of the web Pods
  service:
    type: ClusterIP
    externalPort: 8088

  ## configs generating the `webserver_config.py` file
  ## [FAQ] https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/configuration/airflow-configs.md#webserver_configpy
  webserverConfig:
    ## the full content of the `webserver_config.py` file (as a string)
    stringOverride: |
      from airflow import configuration as conf
      from flask_appbuilder.security.manager import AUTH_DB
      
      # the SQLAlchemy connection string
      SQLALCHEMY_DATABASE_URI = conf.get("core", "SQL_ALCHEMY_CONN")
      
      # use embedded DB for auth
      AUTH_TYPE = AUTH_DB

    ## the name of a Secret containing a `webserver_config.py` key
    existingSecret: ""

# Worker 설정
worker:
  replicas: 2
  persistence:
    size: 2Gi

# Redis 설정
redis:
  enabled: False

# PostgreSQL 설정
postgresql:
  enabled: true
  postgresqlUsername: airflow
  postgresqlPassword: airflow
  postgresqlDatabase: airflow

###################################
# Airflow - DAGs Configs
###################################
dags:
    mountPath: ~
    persistence:
    # Annotations for dags PVC
    annotations: {}
    # Enable persistent volume for storing dags
    enabled: false
    # Volume size for dags
    size: 1Gi
    # If using a custom storageClass, pass name here
    storageClassName:
    # access mode of the persistent volume
    accessMode: ReadWriteOnce
    ## the name of an existing PVC to use
    existingClaim:
    ## optional subpath for dag volume mount
    subPath: ~
    gitSync:
        enabled: true
        repo: git@github.com:torahoo/airflow_test_dags.git
        branch: master
        rev: HEAD
        depth: 1
        subPath: 'dags'
        sshKeySecret: airflow-ssh-git-secret
        containerName: git-sync
        uid: 65533