apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: airflow-cluster1-cert
spec:
  secretName: airflow-cluster1-cert
  commonName: "airflow-cluster1.example.com"
  dnsNames:
    - "airflow-cluster1.example.com"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer